{
  "issue_type": "bug",
  "extracted_from": "/root/yunwei37/vllm-exp/bug-study/analysis_llm/sample_results/vllm/label_based/bug/issues.json",
  "issue": {
    "number": 5311,
    "title": "[Bug]: RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.",
    "body": "### Your current environment\n\n```text\r\nThe output of `python collect_env.py`\r\n```\r\nPyTorch version: 2.1.2+cu121\r\nIs debug build: False\r\nCUDA used to build PyTorch: 12.1\r\nROCM used to build PyTorch: N/A\r\n\r\nOS: Ubuntu 22.04.3 LTS (x86_64)\r\nGCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0\r\nClang version: 14.0.0-1ubuntu1.1\r\nCMake version: Could not collect\r\nLibc version: glibc-2.35\r\n\r\nPython version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)\r\nPython platform: Linux-6.5.0-35-generic-x86_64-with-glibc2.35\r\nIs CUDA available: True\r\nCUDA runtime version: 12.3.107\r\nCUDA_MODULE_LOADING set to: LAZY\r\nGPU models and configuration: \r\nGPU 0: NVIDIA GeForce GTX 1080 Ti\r\nGPU 1: NVIDIA GeForce GTX 1080 Ti\r\nGPU 2: NVIDIA GeForce GTX 1080 Ti\r\nGPU 3: NVIDIA GeForce GTX 1080 Ti\r\n\r\nNvidia driver version: 535.171.04\r\ncuDNN version: Probably one of the following:\r\n/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.7\r\n/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.7\r\nHIP runtime version: N/A\r\nMIOpen runtime version: N/A\r\nIs XNNPACK available: True\r\n\r\nCPU:\r\nArchitecture:                       x86_64\r\nCPU op-mode(s):                     32-bit, 64-bit\r\nAddress sizes:                      46 bits physical, 48 bits virtual\r\nByte Order:                         Little Endian\r\nCPU(s):                             32\r\nOn-line CPU(s) list:                0-31\r\nVendor ID:                          GenuineIntel\r\nModel name:                         Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz\r\nCPU family:                         6\r\nModel:                              79\r\nThread(s) per core:                 2\r\nCore(s) per socket:                 8\r\nSocket(s):                          2\r\nStepping:                           1\r\nCPU max MHz:                        3000.0000\r\nCPU min MHz:                        1200.0000\r\nBogoMIPS:                           4195.10\r\nFlags:                              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm rdt_a rdseed adx smap intel_pt xsaveopt cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts vnmi md_clear flush_l1d\r\nVirtualization:                     VT-x\r\nL1d cache:                          512 KiB (16 instances)\r\nL1i cache:                          512 KiB (16 instances)\r\nL2 cache:                           4 MiB (16 instances)\r\nL3 cache:                           40 MiB (2 instances)\r\nNUMA node(s):                       2\r\nNUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30\r\nNUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31\r\nVulnerability Gather data sampling: Not affected\r\nVulnerability Itlb multihit:        KVM: Mitigation: VMX disabled\r\nVulnerability L1tf:                 Mitigation; PTE Inversion; VMX conditional cache flushes, SMT vulnerable\r\nVulnerability Mds:                  Mitigation; Clear CPU buffers; SMT vulnerable\r\nVulnerability Meltdown:             Mitigation; PTI\r\nVulnerability Mmio stale data:      Mitigation; Clear CPU buffers; SMT vulnerable\r\nVulnerability Retbleed:             Not affected\r\nVulnerability Spec rstack overflow: Not affected\r\nVulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl\r\nVulnerability Spectre v1:           Mitigation; usercopy/swapgs barriers and __user pointer sanitization\r\nVulnerability Spectre v2:           Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP conditional; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected\r\nVulnerability Srbds:                Not affected\r\nVulnerability Tsx async abort:      Mitigation; Clear CPU buffers; SMT vulnerable\r\n\r\nVersions of relevant libraries:\r\n[pip3] numpy==1.26.3\r\n[pip3] nvidia-nccl-cu12==2.18.1\r\n[pip3] torch==2.1.2\r\n[pip3] transformers==4.36.2\r\n[pip3] triton==2.1.0\r\n[conda] Could not collect\r\nROCM Version: Could not collect\r\nNeuron SDK Version: N/A\r\nvLLM Version: 0.2.3\r\nvLLM Build Flags:\r\nCUDA Archs: Not Set; ROCm: Disabled; Neuron: Disabled\r\nGPU Topology:\r\nGPU0\tGPU1\tGPU2\tGPU3\tCPU Affinity\tNUMA Affinity\tGPU NUMA ID\r\nGPU0\t X \tPHB\tSYS\tSYS\t0,2,4,6,8,10\t0\t\tN/A\r\nGPU1\tPHB\t X \tSYS\tSYS\t0,2,4,6,8,10\t0\t\tN/A\r\nGPU2\tSYS\tSYS\t X \tPHB\t1,3,5,7,9,11\t1\t\tN/A\r\nGPU3\tSYS\tSYS\tPHB\t X \t1,3,5,7,9,11\t1\t\tN/A\r\n\r\nLegend:\r\n\r\n  X    = Self\r\n  SYS  = Connection traversing PCIe as well as the SMP interconnect between NUMA nodes (e.g., QPI/UPI)\r\n  NODE = Connection traversing PCIe as well as the interconnect between PCIe Host Bridges within a NUMA node\r\n  PHB  = Connection traversing PCIe as well as a PCIe Host Bridge (typically the CPU)\r\n  PXB  = Connection traversing multiple PCIe bridges (without traversing the PCIe Host Bridge)\r\n  PIX  = Connection traversing at most a single PCIe bridge\r\n  NV#  = Connection traversing a bonded set of # NVLinks\n\n### \ud83d\udc1b Describe the bug\n\nuse triton + vllm backend \r\nImage: nvcr.io/nvidia/tritonserver:24.01-vllm-python-py3   \r\nmodel: opt-125m\r\n\r\ncurl output: {\"error\":\"Error generating stream: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.\"}\r\n\r\ntriton stdout:\r\n\r\nI0606 07:44:10.297581 8157 model.py:275] [vllm] Error generating stream: Task finished unexpectedly. This should never happen! Please open an issue on Github. See stack trace above for the actual cause.\r\n(_AsyncLLMEngine pid=10245) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorkerVllm.execute_method() (pid=10360, ip=10.42.0.27, actor_id=f9f1b30972eea279464b50a801000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x7dd004723760>)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py\", line 31, in execute_method\r\n(_AsyncLLMEngine pid=10245)     return executor(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py\", line 147, in execute_model\r\n(_AsyncLLMEngine pid=10245)     output = self.model_runner.execute_model(seq_group_metadata_list,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py\", line 279, in execute_model\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 313, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(input_ids, positions, kv_caches,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 287, in forward\r\n(_AsyncLLMEngine pid=10245)     return self.decoder(input_ids, positions, kv_caches, input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 259, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = layer(hidden_states, kv_caches[i], input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 164, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.self_attn(hidden_states=hidden_states,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 106, in forward\r\n(_AsyncLLMEngine pid=10245)     attn_output = self.attn(q, k, v, key_cache, value_cache,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/attention.py\", line 156, in forward\r\n(_AsyncLLMEngine pid=10245)     out = xops.memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 244, in memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     return _memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 341, in _memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     out, *_ = op.apply(inp, needs_gradient=False)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 202, in apply\r\n(_AsyncLLMEngine pid=10245)     return cls.apply_bmhk(inp, needs_gradient=needs_gradient)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 266, in apply_bmhk\r\n(_AsyncLLMEngine pid=10245)     out, lse, rng_seed, rng_offset = cls.OPERATOR(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/_ops.py\", line 692, in __call__\r\n(_AsyncLLMEngine pid=10245)     return self._op(*args, **kwargs or {})\r\n(_AsyncLLMEngine pid=10245) RuntimeError: CUDA error: no kernel image is available for execution on the device\r\n(_AsyncLLMEngine pid=10245) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\r\n(_AsyncLLMEngine pid=10245) For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\r\n(_AsyncLLMEngine pid=10245) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\r\n(_AsyncLLMEngine pid=10245) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorkerVllm.execute_method() (pid=10358, ip=10.42.0.27, actor_id=bb92b604606d38c3607c4f7401000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x741ff1dd3790>)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py\", line 31, in execute_method\r\n(_AsyncLLMEngine pid=10245)     return executor(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py\", line 147, in execute_model\r\n(_AsyncLLMEngine pid=10245)     output = self.model_runner.execute_model(seq_group_metadata_list,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py\", line 279, in execute_model\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 313, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(input_ids, positions, kv_caches,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 287, in forward\r\n(_AsyncLLMEngine pid=10245)     return self.decoder(input_ids, positions, kv_caches, input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 259, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = layer(hidden_states, kv_caches[i], input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 164, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.self_attn(hidden_states=hidden_states,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 106, in forward\r\n(_AsyncLLMEngine pid=10245)     attn_output = self.attn(q, k, v, key_cache, value_cache,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/attention.py\", line 156, in forward\r\n(_AsyncLLMEngine pid=10245)     out = xops.memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 244, in memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     return _memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 341, in _memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     out, *_ = op.apply(inp, needs_gradient=False)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 202, in apply\r\n(_AsyncLLMEngine pid=10245)     return cls.apply_bmhk(inp, needs_gradient=needs_gradient)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 266, in apply_bmhk\r\n(_AsyncLLMEngine pid=10245)     out, lse, rng_seed, rng_offset = cls.OPERATOR(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/_ops.py\", line 692, in __call__\r\n(_AsyncLLMEngine pid=10245)     return self._op(*args, **kwargs or {})\r\n(_AsyncLLMEngine pid=10245) RuntimeError: CUDA error: no kernel image is available for execution on the device\r\n(_AsyncLLMEngine pid=10245) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\r\n(_AsyncLLMEngine pid=10245) For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\r\n(_AsyncLLMEngine pid=10245) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\r\n(_AsyncLLMEngine pid=10245) Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::RayWorkerVllm.execute_method() (pid=10361, ip=10.42.0.27, actor_id=9294639f58f94e6c005fb99f01000000, repr=<vllm.engine.ray_utils.RayWorkerVllm object at 0x79cc90adf760>)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/engine/ray_utils.py\", line 31, in execute_method\r\n(_AsyncLLMEngine pid=10245)     return executor(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/worker.py\", line 147, in execute_model\r\n(_AsyncLLMEngine pid=10245)     output = self.model_runner.execute_model(seq_group_metadata_list,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py\", line 115, in decorate_context\r\n(_AsyncLLMEngine pid=10245)     return func(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/worker/model_runner.py\", line 279, in execute_model\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 313, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.model(input_ids, positions, kv_caches,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 287, in forward\r\n(_AsyncLLMEngine pid=10245)     return self.decoder(input_ids, positions, kv_caches, input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 259, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = layer(hidden_states, kv_caches[i], input_metadata,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 164, in forward\r\n(_AsyncLLMEngine pid=10245)     hidden_states = self.self_attn(hidden_states=hidden_states,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/models/opt.py\", line 106, in forward\r\n(_AsyncLLMEngine pid=10245)     attn_output = self.attn(q, k, v, key_cache, value_cache,\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1518, in _wrapped_call_impl\r\n(_AsyncLLMEngine pid=10245)     return self._call_impl(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py\", line 1527, in _call_impl\r\n(_AsyncLLMEngine pid=10245)     return forward_call(*args, **kwargs)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/vllm/model_executor/layers/attention.py\", line 156, in forward\r\n(_AsyncLLMEngine pid=10245)     out = xops.memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 244, in memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     return _memory_efficient_attention_forward(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/__init__.py\", line 341, in _memory_efficient_attention_forward\r\n(_AsyncLLMEngine pid=10245)     out, *_ = op.apply(inp, needs_gradient=False)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 202, in apply\r\n(_AsyncLLMEngine pid=10245)     return cls.apply_bmhk(inp, needs_gradient=needs_gradient)\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/xformers/ops/fmha/cutlass.py\", line 266, in apply_bmhk\r\n(_AsyncLLMEngine pid=10245)     out, lse, rng_seed, rng_offset = cls.OPERATOR(\r\n(_AsyncLLMEngine pid=10245)   File \"/usr/local/lib/python3.10/dist-packages/torch/_ops.py\", line 692, in __call__\r\n(_AsyncLLMEngine pid=10245)     return self._op(*args, **kwargs or {})\r\n(_AsyncLLMEngine pid=10245) RuntimeError: CUDA error: no kernel image is available for execution on the device\r\n(_AsyncLLMEngine pid=10245) CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.\r\n(_AsyncLLMEngine pid=10245) For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\r\n(_AsyncLLMEngine pid=10245) Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.\r\n\r\n",
    "labels": [
      "bug"
    ],
    "state": "closed",
    "created_at": "2024-06-06T07:50:01+00:00",
    "closed_at": "2025-02-11T16:43:28+00:00",
    "comments": 3,
    "reactions": {
      "url": "https://api.github.com/repos/vllm-project/vllm/issues/5311/reactions",
      "total_count": 4,
      "+1": 4,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "author_association": "NONE",
    "html_url": "https://github.com/vllm-project/vllm/issues/5311"
  }
}